//! Ethernet driver for the SLSTK3701A board.
//!
//! Uses the Cadence GEM MAC in RMII mode with the KSZ8091RNA PHY.
//!
//! # Hardware overview
//!
//! The EFM32GG11B integrates a Cadence GEM (Gigabit Ethernet MAC) controller.
//! On the SLSTK3701A starter kit it is wired in RMII mode to a Microchip
//! KSZ8091RNA 10/100 Ethernet PHY at MDIO address 0.  The PHY connects to
//! an RJ-45 jack with integrated magnetics.
//!
//! Data flows through three clock domains:
//!
//!  1. **AHB bus clock (HFCLK, 19 MHz HFRCO)** -- the DMA engine reads TX
//!     descriptors and frame data from SRAM, and writes received frames back.
//!  2. **RMII reference clock (50 MHz HFXO)** -- clocks the 2-bit TX/RX data
//!     buses between MAC and PHY.  Generated by CMU_CLKOUT2 on PD10.
//!  3. **MDIO clock (~2.4 MHz)** -- management bus for PHY register access,
//!     derived from HFCLK via a programmable divider.
//!
//! # MII vs RMII
//!
//! MII (Media Independent Interface) is the standard interface between the MAC
//! (inside the EFM32GG11B) and the PHY (KSZ8091RNA, which drives the wire).
//! It uses 16+ data pins: 4-bit TX, 4-bit RX, clocks, and control signals,
//! clocked at 25 MHz for 100 Mbps.
//!
//! RMII (Reduced MII) halves the pin count by narrowing data buses to 2 bits
//! each and doubling the clock to 50 MHz -- same throughput, fewer PCB traces.
//! The SLSTK3701A uses RMII.
//!
//! MDIO (Management Data I/O) is a separate 2-wire bus (MDC + MDIO) for
//! reading/writing PHY registers.  It works the same regardless of MII/RMII.
//!
//! # REFCLK generation
//!
//! The 50 MHz RMII reference clock is output by the MCU, not the PHY.  The
//! KSZ8091RNA is hardware-strapped to REFCLK-input mode (PHY Control 2
//! register bit 7 reads as 0 and cannot be set to 1).
//!
//! HFXO (50 MHz crystal oscillator) feeds CMU_CLKOUT2, which is routed to
//! PD10 at location 5.  The signal reaches the PHY's XI/REFCLK pin through
//! a 49.9 ohm series resistor (R118 on the board).
//!
//! **Critical quirk:** switching HFCLK to HFXO disables CMU_CLKOUT2's raw
//! HFXO output -- the signal drops to 0.  HFCLK must therefore stay on
//! HFRCO (19 MHz).  The MAC's TX engine uses an internal reference clock
//! (TXREFCLKSEL = 1) rather than reading REFCLK back from the pad.
//!
//! # DMA descriptors (Cadence GEM)
//!
//! The GEM uses linked-list descriptor rings in SRAM for both TX and RX.
//! Each descriptor is 8 bytes (two 32-bit words).  The last descriptor in
//! each ring has a WRAP bit set so the hardware wraps back to the first.
//!
//! **RX descriptor word 0:** bits\[31:2\] = buffer address, bit 1 = wrap,
//! bit 0 = ownership (0 = HW owns, 1 = SW owns / frame received).
//!
//! **TX descriptor word 1:** bit 31 = used (1 = SW owns), bit 30 = wrap,
//! bit 15 = last buffer in frame, bits\[13:0\] = byte length.
//!
//! # ETH_CTRL register settings
//!
//!   MIISEL = 0     RMII mode (Silicon Labs convention: 0 = RMII, 1 = MII)
//!   GBLCLKEN = 1   enable MAC internal clocks (tsu, tx, rx, ref)
//!   TXREFCLKSEL = 1  TX engine uses internal ref_clk, not pad input
//!
//! # ETH interrupts
//!
//! The Cadence GEM supports a rich interrupt set.  By default this driver
//! uses polling (`rx_available()`), which is simplest.  Call
//! `enable_interrupts()` after `init()` to enable the RXCMPLT and TXCMPLT
//! interrupts.  The ISR sets atomic event flags that the main loop can
//! check, allowing the CPU to sleep via WFI between Ethernet events.
//!
//! The caller must unmask `pac::Interrupt::ETH` in the NVIC and provide
//! an `#[interrupt] fn ETH()` handler that calls `eth::irq_handler()`.
//!
//! # Pin mapping (SLSTK3701A, RMII Location 1)
//!
//! ```text
//!   PF7  - TXD0        PD9  - RXD0
//!   PF6  - TXD1        PF9  - RXD1
//!   PF8  - TXEN        PD11 - CRSDV
//!   PD10 - REFCLK      PD13 - MDIO
//!   PD14 - MDC
//!   PH7  - PHY_RST# (active low)
//!   PI10 - PHY power enable (active high)
//! ```

use core::ptr::{self, addr_of, addr_of_mut};
use core::sync::atomic::{AtomicBool, Ordering};

use efm32gg11b_pac as pac;

// ---------- interrupt event flags ----------

/// Set by the ISR when a frame has been received (RXCMPLT).
static RX_EVENT: AtomicBool = AtomicBool::new(false);
/// Set by the ISR when a frame has been transmitted (TXCMPLT).
static TX_EVENT: AtomicBool = AtomicBool::new(false);

// ---------- constants ----------

const PHY_ADDR: u8 = 0;

/// Locally-administered MAC address.
const MAC: [u8; 6] = [0x02, 0x00, 0x00, 0x47, 0x11, 0xBB];

const RX_DESC_COUNT: usize = 8;
const TX_DESC_COUNT: usize = 4;
const RX_BUF_SIZE: usize = 1536;
const TX_BUF_SIZE: usize = 1536;

// PHY register addresses (IEEE 802.3)
const PHY_REG_BMCR: u8 = 0; // Basic Mode Control
const PHY_REG_BMSR: u8 = 1; // Basic Mode Status
const PHY_REG_PHYID1: u8 = 2; // PHY Identifier 1
const PHY_REG_PHYID2: u8 = 3; // PHY Identifier 2

// BMCR bits
const BMCR_RESET: u16 = 1 << 15;
const BMCR_AUTONEG_EN: u16 = 1 << 12;
const BMCR_RESTART_AUTONEG: u16 = 1 << 9;

// BMSR bits
const BMSR_LINK_STATUS: u16 = 1 << 2;
const BMSR_AUTONEG_COMPLETE: u16 = 1 << 5;

// ---------- DMA descriptor types ----------

/// Cadence GEM RX buffer descriptor.
#[repr(C, align(8))]
struct RxDesc {
    /// Word 0: bits[31:2] = buffer address, bit[1] = wrap, bit[0] = ownership (1=SW owns).
    addr: u32,
    /// Word 1: status (set by hardware).
    status: u32,
}

/// Cadence GEM TX buffer descriptor.
#[repr(C, align(8))]
struct TxDesc {
    /// Word 0: buffer address.
    addr: u32,
    /// Word 1: bit[31] = used, bit[30] = wrap, bit[15] = last, bits[13:0] = length.
    status: u32,
}

// ---------- static buffers ----------

// RX descriptor status bits
const RX_DESC_OWNERSHIP: u32 = 1 << 0;
const RX_DESC_WRAP: u32 = 1 << 1;
const RX_DESC_SOF: u32 = 1 << 14;
const RX_DESC_EOF: u32 = 1 << 15;
const RX_DESC_LEN_MASK: u32 = 0x1FFF;

// TX descriptor status bits
const TX_DESC_USED: u32 = 1 << 31;
const TX_DESC_WRAP: u32 = 1 << 30;
const TX_DESC_LAST: u32 = 1 << 15;
const TX_DESC_LEN_MASK: u32 = 0x3FFF;

static mut RX_DESC_RING: [RxDesc; RX_DESC_COUNT] = {
    const INIT: RxDesc = RxDesc { addr: 0, status: 0 };
    [INIT; RX_DESC_COUNT]
};
static mut TX_DESC_RING: [TxDesc; TX_DESC_COUNT] = {
    const INIT: TxDesc = TxDesc { addr: 0, status: 0 };
    [INIT; TX_DESC_COUNT]
};
// DMA buffers must be word-aligned for the Cadence GEM.
#[repr(C, align(4))]
struct AlignedBuf<const N: usize>([u8; N]);

static mut RX_BUFS: [AlignedBuf<RX_BUF_SIZE>; RX_DESC_COUNT] = {
    const INIT: AlignedBuf<RX_BUF_SIZE> = AlignedBuf([0; RX_BUF_SIZE]);
    [INIT; RX_DESC_COUNT]
};
static mut TX_BUFS: [AlignedBuf<TX_BUF_SIZE>; TX_DESC_COUNT] = {
    const INIT: AlignedBuf<TX_BUF_SIZE> = AlignedBuf([0; TX_BUF_SIZE]);
    [INIT; TX_DESC_COUNT]
};

/// Current RX descriptor index (for software polling).
static mut RX_IDX: usize = 0;
/// Current TX descriptor index.
static mut TX_IDX: usize = 0;

// ---------- PAC accessors ----------

fn eth() -> &'static pac::eth::RegisterBlock {
    // SAFETY: single-threaded bare-metal; ETH peripheral is only used by this module.
    unsafe { &*pac::Eth::ptr() }
}

fn gpio() -> &'static pac::gpio::RegisterBlock {
    // SAFETY: single-threaded bare-metal context.
    unsafe { &*pac::Gpio::ptr() }
}

// ---------- GPIO helpers ----------

/// Set bits in a GPIO DOUT register (read-modify-write).
///
/// EFM32 GPIO has no atomic DOUTSET register, so we must use read-modify-write
/// on DOUT.  This is safe in single-threaded bare-metal code.
fn gpio_set(
    dout: &pac::generic::Reg<
        impl pac::generic::Writable + pac::generic::Readable + pac::generic::RegisterSpec<Ux = u32>,
    >,
    mask: u32,
) {
    dout.modify(|r, w| unsafe { w.bits(r.bits() | mask) });
}

/// Clear bits in a GPIO DOUT register (read-modify-write).
fn gpio_clear(
    dout: &pac::generic::Reg<
        impl pac::generic::Writable + pac::generic::Readable + pac::generic::RegisterSpec<Ux = u32>,
    >,
    mask: u32,
) {
    dout.modify(|r, w| unsafe { w.bits(r.bits() & !mask) });
}

// ---------- delay ----------

/// Delay in milliseconds.  Uses 50k cycles/ms which is correct at 50 MHz
/// and conservatively longer at the actual 19 MHz HFRCO clock.
#[inline]
fn delay_ms(ms: u32) {
    cortex_m::asm::delay(ms * 50_000);
}

// ---------- MDIO ----------

/// Read a PHY register via MDIO (Clause 22).
///
/// MDIO uses a 2-wire serial bus (MDC clock + MDIO data) separate from the
/// RMII data path.  The Cadence GEM handles the MDIO frame format: preamble,
/// start-of-frame, opcode, PHY/register address, turnaround, and data.
pub fn mdio_read(reg: u8) -> u16 {
    let e = eth();
    while e.networkstatus().read().mandone().bit_is_clear() {}

    let val: u32 = (1 << 30)         // WRITE1 = 1 (Clause 22)
        | (0b10 << 28)               // OPERATION = read
        | ((PHY_ADDR as u32) << 23)  // PHYADDR
        | ((reg as u32) << 18)       // REGADDR
        | (0b10 << 16); // WRITE10 = 0b10
                        // SAFETY: PHYMNGMNT is a raw-bits register with no safe field accessors.
    e.phymngmnt().write(|w| unsafe { w.bits(val) });

    while e.networkstatus().read().mandone().bit_is_clear() {}
    (e.phymngmnt().read().bits() & 0xFFFF) as u16
}

/// Write a PHY register via MDIO (Clause 22).
pub fn mdio_write(reg: u8, data: u16) {
    let e = eth();
    while e.networkstatus().read().mandone().bit_is_clear() {}

    let val: u32 = (1 << 30)         // WRITE1 = 1 (Clause 22)
        | (0b01 << 28)               // OPERATION = write
        | ((PHY_ADDR as u32) << 23)  // PHYADDR
        | ((reg as u32) << 18)       // REGADDR
        | (0b10 << 16)               // WRITE10 = 0b10
        | (data as u32); // PHYRWDATA
                         // SAFETY: PHYMNGMNT is a raw-bits register with no safe field accessors.
    e.phymngmnt().write(|w| unsafe { w.bits(val) });

    while e.networkstatus().read().mandone().bit_is_clear() {}
}

// ---------- public API ----------

/// Return the board's MAC address.
pub fn mac_address() -> [u8; 6] {
    MAC
}

/// Check if a TX descriptor is available for sending.
pub fn tx_available() -> bool {
    // SAFETY: single-threaded; TX_IDX and TX_DESC_RING only mutated by tx_packet().
    // Volatile read needed because the DMA engine writes the USED bit.
    unsafe {
        let idx = ptr::read_volatile(addr_of!(TX_IDX));
        let status = ptr::read_volatile(addr_of!(TX_DESC_RING[idx].status));
        status & TX_DESC_USED != 0
    }
}

/// One-time initialisation: clocks, GPIO, RMII routing, MAC, DMA, PHY.
///
/// Init order follows the CycloneTCP reference: GPIO pins -> CMU_CLKOUT2 ->
/// HFXO -> ETH peripheral clock -> ETH config -> PHY power/reset -> PHY init.
/// HFCLK stays on HFRCO (19 MHz); the MAC reads REFCLK from PD10.
pub fn init() {
    // SAFETY: single-threaded bare-metal; CMU peripheral used only here.
    let cmu = unsafe { &*pac::Cmu::ptr() };
    let gpio = gpio();
    let e = eth();

    // ---- Step 1: Configure ALL GPIO pins (before any peripheral clocks) ----

    // Port D: RMII data + MDIO + REFCLK output.
    //
    // Drive strength and slew rate are left at defaults (standard drive,
    // slewrate = 5).  PD10 carries the 50 MHz REFCLK, but it is driven by
    // the CMU clock-output hardware, which bypasses the GPIO output driver
    // entirely -- PD_CTRL settings have no effect on CMU_CLKOUT signals.
    // MDIO (PD13) and MDC (PD14) run at ~2.4 MHz, well within the default
    // slew rate capability.
    gpio.pd_modeh().modify(|_, w| {
        w.mode9()
            .input() // RXD0
            .mode10()
            .pushpull() // REFCLK (CMU_CLKOUT2 output)
            .mode11()
            .input() // CRSDV
            .mode13()
            .pushpull() // MDIO
            .mode14()
            .pushpull() // MDC
    });

    // Port F: RMII TX data + RXD1.
    gpio.pf_model().modify(|_, w| {
        w.mode6()
            .pushpull() // TXD1
            .mode7()
            .pushpull() // TXD0
    });
    gpio.pf_modeh().modify(|_, w| {
        w.mode8()
            .pushpull() // TXEN
            .mode9()
            .input() // RXD1
    });

    // PHY power (PI10) and reset (PH7) pins -- configure but don't power yet.
    gpio.pi_modeh().modify(|_, w| w.mode10().pushpull());
    gpio.ph_model().modify(|_, w| w.mode7().pushpull());
    gpio_clear(gpio.pi_dout(), 1 << 10); // PI10 low = PHY power off
    gpio_clear(gpio.ph_dout(), 1 << 7); // PH7 low = PHY in reset

    // ---- Step 2: Configure CMU_CLKOUT2 routing (before HFXO is running) ----
    cmu.ctrl().modify(|_, w| w.clkoutsel2().hfxo());
    cmu.routeloc0().modify(|_, w| w.clkout2loc().loc5()); // PD10
    cmu.routepen().modify(|_, w| w.clkout2pen().set_bit());

    // ---- Step 3: Enable HFXO -- REFCLK appears on PD10 ----
    // HFCLK stays on HFRCO (19 MHz).  Switching to HFXO kills CMU_CLKOUT2.
    cmu.oscencmd().write(|w| w.hfxoen().set_bit());
    while cmu.status().read().hfxordy().bit_is_clear() {}
    delay_ms(1); // let REFCLK stabilize

    let ones_refclk = sample_pd10(gpio);
    defmt::info!("PD10 CLKOUT2 HFXO: {}/1000", ones_refclk);

    // ---- Step 4: Enable ETH peripheral clock (REFCLK is already running) ----
    cmu.hfbusclken0().modify(|_, w| w.eth().set_bit());
    let _ = cmu.hfbusclken0().read(); // sync

    // ---- Step 5: ETH configuration ----

    // GBLCLKEN = 1: enable internal clocks (tsu_clk, tx_clk, rx_clk, ref_clk).
    // MIISEL = 0: RMII mode (0 = RMII, 1 = MII per Silicon Labs headers).
    // TXREFCLKSEL = 1: TX engine uses internal ref_clk (not pad input).
    e.ctrl()
        .write(|w| w.gblclken().set_bit().txrefclksel().set_bit());

    // Pin routing: RMII loc1, MDIO loc1.
    e.routeloc1().write(|w| w.rmiiloc().loc1().mdioloc().loc1());
    e.routepen()
        .write(|w| w.rmiipen().set_bit().mdiopen().set_bit());

    // Network configuration.
    e.networkcfg().write(|w| {
        w.speed()
            .set_bit() // 100 Mbps
            .fullduplex()
            .set_bit()
            .mdcclkdiv()
            .divby8() // 19 MHz / 8 ~ 2.4 MHz (MDIO spec: max 2.5 MHz)
            .fcsremove()
            .set_bit()
            .rxchksumoffloaden()
            .set_bit()
            .rx1536byteframes()
            .set_bit()
    });

    // DMA configuration.
    // SAFETY: ambabrstlen and rxbufsize are raw-bits fields without enum variants.
    e.dmacfg().write(|w| unsafe {
        w.ambabrstlen()
            .bits(4) // AHB burst length = 4
            .rxpbufsize()
            .size3() // full RX packet buffer
            .txpbufsize()
            .set_bit() // full TX packet buffer
            .rxbufsize()
            .bits(24) // 24 * 64 = 1536 bytes per descriptor
            .frcdiscardonerr()
            .set_bit()
    });

    // Init DMA descriptors.
    init_dma_descriptors();

    // Point hardware to descriptor rings.
    // SAFETY: writing raw descriptor-ring base addresses into RXQPTR / TXQPTR.
    e.rxqptr()
        .write(|w| unsafe { w.bits(addr_of!(RX_DESC_RING) as u32) });
    e.txqptr()
        .write(|w| unsafe { w.bits(addr_of!(TX_DESC_RING) as u32) });

    // MAC address (little-endian register layout).
    let mac = MAC;
    let bottom = u32::from(mac[0])
        | (u32::from(mac[1]) << 8)
        | (u32::from(mac[2]) << 16)
        | (u32::from(mac[3]) << 24);
    let top = u32::from(mac[4]) | (u32::from(mac[5]) << 8);
    // SAFETY: SPECADDR registers are raw-bits.
    e.specaddr1bottom().write(|w| unsafe { w.bits(bottom) });
    e.specaddr1top().write(|w| unsafe { w.bits(top) });

    // Enable management port (needed for MDIO/PHY communication).
    e.networkctrl().write(|w| w.manporten().set_bit());

    // Clear pending interrupts and status (write-1-to-clear registers).
    // SAFETY: writing raw clear masks.
    e.ifcr().write(|w| unsafe { w.bits(0xFFFF_FFFF) });
    e.txstatus().write(|w| unsafe { w.bits(0xFF) });
    e.rxstatus().write(|w| unsafe { w.bits(0x0F) });

    // ---- Step 6: PHY power and reset (ETH + REFCLK both running) ----
    gpio_set(gpio.pi_dout(), 1 << 10); // PI10 high = PHY power on
    delay_ms(10);
    gpio_set(gpio.ph_dout(), 1 << 7); // PH7 high = release reset
    delay_ms(10);

    // Diagnostic: REFCLK after PHY is out of reset.
    let ones_post = sample_pd10(gpio);
    defmt::info!("PD10 after PHY reset: {}/1000", ones_post);

    // ---- Step 7: PHY init via MDIO ----
    phy_init();

    // ---- Step 8: Enable RX and TX ----
    e.networkctrl()
        .modify(|_, w| w.enbrx().set_bit().enbtx().set_bit());
}

/// Check if the PHY link is up.
pub fn link_up() -> bool {
    mdio_read(PHY_REG_BMSR) & BMSR_LINK_STATUS != 0
}

/// Dump ETH status registers for diagnostics.
///
/// Kept intentionally lightweight -- tight GPIO sampling loops can starve
/// the ETH DMA engine on the shared AHB bus and cause bus faults.
pub fn dump_status() {
    let e = eth();
    let rxs = e.rxstatus().read().bits();
    let txs = e.txstatus().read().bits();
    let ns = e.networkstatus().read().bits();
    defmt::info!("ETH rxs={:08x} txs={:08x} ns={:08x}", rxs, txs, ns);
}

/// Check if a received frame is available.
pub fn rx_available() -> bool {
    // SAFETY: single-threaded; volatile read needed because DMA writes this word.
    unsafe {
        let idx = ptr::read_volatile(addr_of!(RX_IDX));
        let addr_word = ptr::read_volatile(addr_of!(RX_DESC_RING[idx].addr));
        addr_word & RX_DESC_OWNERSHIP != 0
    }
}

/// Get a reference to the received frame data and its length.
/// Returns `None` if no frame is available.
/// Caller MUST call [`rx_release`] after processing.
pub fn rx_packet() -> Option<&'static [u8]> {
    // SAFETY: single-threaded bare-metal.  Volatile reads are required because
    // the DMA engine writes descriptor words concurrently.  The returned slice
    // borrows from a static buffer that is valid for the 'static lifetime; the
    // caller must call rx_release() before the DMA reuses the buffer.
    unsafe {
        let idx = ptr::read_volatile(addr_of!(RX_IDX));
        let addr_word = ptr::read_volatile(addr_of!(RX_DESC_RING[idx].addr));
        if addr_word & RX_DESC_OWNERSHIP == 0 {
            return None;
        }
        let status = ptr::read_volatile(addr_of!(RX_DESC_RING[idx].status));
        // We only handle single-buffer frames (SOF + EOF in one descriptor).
        if status & RX_DESC_SOF == 0 || status & RX_DESC_EOF == 0 {
            rx_release();
            return None;
        }
        let len = (status & RX_DESC_LEN_MASK) as usize;
        let len = len.min(RX_BUF_SIZE);
        let buf = addr_of!(RX_BUFS[idx].0) as *const u8;
        Some(core::slice::from_raw_parts(buf, len))
    }
}

/// Release the current RX descriptor back to the DMA engine.
pub fn rx_release() {
    // SAFETY: single-threaded bare-metal.  Volatile writes are required so the
    // DMA engine observes the ownership handoff.
    unsafe {
        let idx = ptr::read_volatile(addr_of!(RX_IDX));
        let buf_addr = addr_of!(RX_BUFS[idx].0) as u32;
        let mut addr_word = buf_addr & !0x3; // low 2 bits are flags, not address
        if idx == RX_DESC_COUNT - 1 {
            addr_word |= RX_DESC_WRAP;
        }
        // Clear ownership bit (0 = HW owns).
        ptr::write_volatile(addr_of_mut!(RX_DESC_RING[idx].addr), addr_word);
        ptr::write_volatile(addr_of_mut!(RX_DESC_RING[idx].status), 0);
        ptr::write_volatile(addr_of_mut!(RX_IDX), (idx + 1) % RX_DESC_COUNT);
    }
}

/// Transmit an Ethernet frame.  Returns `true` if the frame was queued.
pub fn tx_packet(data: &[u8]) -> bool {
    if data.len() > TX_BUF_SIZE || data.is_empty() {
        return false;
    }

    // SAFETY: single-threaded bare-metal.  Volatile accesses are required
    // because the DMA engine reads descriptors and writes the USED bit.
    unsafe {
        let idx = ptr::read_volatile(addr_of!(TX_IDX));
        let status = ptr::read_volatile(addr_of!(TX_DESC_RING[idx].status));
        if status & TX_DESC_USED == 0 {
            return false; // descriptor still owned by hardware
        }

        // Copy frame data into the DMA buffer.
        let dst = addr_of_mut!(TX_BUFS[idx].0) as *mut u8;
        ptr::copy_nonoverlapping(data.as_ptr(), dst, data.len());

        // Write descriptor fields.
        let buf_addr = addr_of!(TX_BUFS[idx].0) as u32;
        ptr::write_volatile(addr_of_mut!(TX_DESC_RING[idx].addr), buf_addr);
        let mut ctrl = (data.len() as u32) & TX_DESC_LEN_MASK;
        ctrl |= TX_DESC_LAST; // single-buffer frame
        if idx == TX_DESC_COUNT - 1 {
            ctrl |= TX_DESC_WRAP;
        }
        // Clear USED bit (0 = HW can transmit).
        ptr::write_volatile(addr_of_mut!(TX_DESC_RING[idx].status), ctrl);

        // DSB ensures the DMA engine sees descriptor writes before we trigger TX.
        cortex_m::asm::dsb();

        ptr::write_volatile(addr_of_mut!(TX_IDX), (idx + 1) % TX_DESC_COUNT);

        // Trigger transmission.
        eth().networkctrl().modify(|_, w| w.txstrt().set_bit());
        true
    }
}

// ---------- interrupt support ----------

/// Enable RXCMPLT and TXCMPLT interrupts on the Cadence GEM.
///
/// The caller must also:
///   1. Unmask `pac::Interrupt::ETH` in the NVIC
///   2. Provide an `#[interrupt] fn ETH()` that calls `eth::irq_handler()`
pub fn enable_interrupts() {
    let e = eth();
    // Clear any pending flags first.
    e.ifcr().write(|w| unsafe { w.bits(0xFFFF_FFFF) });
    // Enable RXCMPLT (bit 1) and TXCMPLT (bit 7).
    e.iens()
        .write(|w| w.rxcmplt().set_bit().txcmplt().set_bit());
}

/// ETH interrupt handler.  Call this from the `#[interrupt] fn ETH()` ISR.
///
/// Clears the interrupt flags and sets atomic event flags that the main
/// loop can consume via `take_rx_event()` / `take_tx_event()`.
pub fn irq_handler() {
    let e = eth();
    let status = e.ifcr().read();
    // Write-1-to-clear the flags we handle.
    e.ifcr().write(|w| unsafe { w.bits(status.bits()) });

    if status.rxcmplt().bit_is_set() {
        RX_EVENT.store(true, Ordering::Release);
    }
    if status.txcmplt().bit_is_set() {
        TX_EVENT.store(true, Ordering::Release);
    }
}

/// Check and clear the RX event flag (set by the ISR on RXCMPLT).
pub fn take_rx_event() -> bool {
    RX_EVENT.swap(false, Ordering::Acquire)
}

/// Check and clear the TX event flag (set by the ISR on TXCMPLT).
pub fn take_tx_event() -> bool {
    TX_EVENT.swap(false, Ordering::Acquire)
}

// ---------- internal ----------

/// Sample PD10 1000 times with variable delays to detect clock presence.
///
/// A 50 MHz signal toggling at the GPIO sampling rate should read ~400-550
/// out of 1000.  A stuck-low or stuck-high pin reads near 0 or 1000.
/// Only safe to call during init, before ETH DMA is active.
fn sample_pd10(gpio: &pac::gpio::RegisterBlock) -> u32 {
    let mut ones: u32 = 0;
    for i in 0u32..1000 {
        for _ in 0..(i % 5) {
            cortex_m::asm::nop();
        }
        if gpio.pd_din().read().bits() & (1 << 10) != 0 {
            ones += 1;
        }
    }
    ones
}

fn init_dma_descriptors() {
    // SAFETY: called once during init before DMA is enabled.
    unsafe {
        for i in 0..RX_DESC_COUNT {
            let buf_addr = addr_of!(RX_BUFS[i].0) as u32;
            let mut addr_word = buf_addr & !0x3;
            if i == RX_DESC_COUNT - 1 {
                addr_word |= RX_DESC_WRAP;
            }
            // Ownership = 0 (HW owns).
            ptr::write_volatile(addr_of_mut!(RX_DESC_RING[i].addr), addr_word);
            ptr::write_volatile(addr_of_mut!(RX_DESC_RING[i].status), 0);
        }

        for i in 0..TX_DESC_COUNT {
            let buf_addr = addr_of!(TX_BUFS[i].0) as u32;
            ptr::write_volatile(addr_of_mut!(TX_DESC_RING[i].addr), buf_addr);
            let mut ctrl = TX_DESC_USED; // SW owns initially (used = 1)
            if i == TX_DESC_COUNT - 1 {
                ctrl |= TX_DESC_WRAP;
            }
            ptr::write_volatile(addr_of_mut!(TX_DESC_RING[i].status), ctrl);
        }
    }
}

fn phy_init() {
    // Read PHY ID to verify KSZ8091RNA (expected OUI: 0x0022, model 0x1561).
    let id1 = mdio_read(PHY_REG_PHYID1);
    let id2 = mdio_read(PHY_REG_PHYID2);
    defmt::info!("PHY ID: {:04x}:{:04x}", id1, id2);

    // Dump KSZ8091RNA control registers for REFCLK diagnostics.
    let reg1e = mdio_read(0x1E); // PHY Control 1
    let reg1f = mdio_read(0x1F); // PHY Control 2 (bit 7 = RMII REFCLK select)
    defmt::info!("PHY reg1E={:04x} reg1F={:04x}", reg1e, reg1f);

    // Soft-reset the PHY.
    mdio_write(PHY_REG_BMCR, BMCR_RESET);
    let mut timeout = 100;
    while mdio_read(PHY_REG_BMCR) & BMCR_RESET != 0 && timeout > 0 {
        delay_ms(10);
        timeout -= 1;
    }

    // Enable and restart auto-negotiation.
    mdio_write(PHY_REG_BMCR, BMCR_AUTONEG_EN | BMCR_RESTART_AUTONEG);

    defmt::info!("Waiting for PHY auto-negotiation...");
    timeout = 500; // 5 seconds
    while timeout > 0 {
        let bmsr = mdio_read(PHY_REG_BMSR);
        if bmsr & BMSR_AUTONEG_COMPLETE != 0 {
            defmt::info!("Auto-negotiation complete");
            break;
        }
        delay_ms(10);
        timeout -= 1;
    }
    if timeout == 0 {
        defmt::warn!("Auto-negotiation timed out");
    }

    if mdio_read(PHY_REG_BMSR) & BMSR_LINK_STATUS != 0 {
        defmt::info!("Link is UP");
    } else {
        defmt::warn!("Link is DOWN");
    }
}
