[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip EFM32GG11B820F2048GL192"

rustflags = [
  "-C",
  "linker=flip-link",
  "-C",
  "link-arg=--nmagic",
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tdefmt.x",

  # Code-size optimizations.
  #   trap unreachable can save a lot of space, but requires nightly compiler.
  #   uncomment the next line if you wish to enable it
  # "-Z", "trap-unreachable=no",
  "-C",
  "inline-threshold=5",
  "-C",
  "no-vectorize-loops",

  # Optimize for code size, performance notwithstanding.
  "-C", "opt-level=z",
]

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"

[profile.release]
debug = 2
