[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = ["probe-rs", "run", "--log-format", "{L} {s}", "--probe", "1366:0105:000440300487", "--chip", "EFM32GG11B820F2048GL192", "--protocol", "swd"]

rustflags = [
  "-C",
  "linker=flip-link",
  "-C",
  "link-arg=--nmagic",
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tdefmt.x",

  "-C",
  "llvm-args=--inline-threshold=5",
  "-C",
  "no-vectorize-loops",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
