#![doc = "Peripheral access API for EFM32GG11B820F2048GL192 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
pub use cortex_m::peripheral::Peripherals as CorePeripherals;
pub use cortex_m::peripheral::{CBP, CPUID, DCB, DWT, FPB, FPU, ITM, MPU, NVIC, SCB, SYST, TPIU};
#[cfg(feature = "rt")]
pub use cortex_m_rt::interrupt;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn EMU();
    fn WDOG0();
    fn LDMA();
    fn GPIO_EVEN();
    fn SMU();
    fn TIMER0();
    fn USART0_RX();
    fn USART0_TX();
    fn ACMP0();
    fn ADC0();
    fn IDAC0();
    fn I2C0();
    fn I2C1();
    fn GPIO_ODD();
    fn TIMER1();
    fn TIMER2();
    fn TIMER3();
    fn USART1_RX();
    fn USART1_TX();
    fn USART2_RX();
    fn USART2_TX();
    fn UART0_RX();
    fn UART0_TX();
    fn UART1_RX();
    fn UART1_TX();
    fn LEUART0();
    fn LEUART1();
    fn LETIMER0();
    fn PCNT0();
    fn PCNT1();
    fn PCNT2();
    fn RTCC();
    fn CMU();
    fn MSC();
    fn CRYPTO0();
    fn CRYOTIMER();
    fn FPUEH();
    fn USART3_RX();
    fn USART3_TX();
    fn USART4_RX();
    fn USART4_TX();
    fn WTIMER0();
    fn WTIMER1();
    fn WTIMER2();
    fn WTIMER3();
    fn I2C2();
    fn VDAC0();
    fn TIMER4();
    fn TIMER5();
    fn TIMER6();
    fn USART5_RX();
    fn USART5_TX();
    fn CSEN();
    fn LESENSE();
    fn EBI();
    fn ACMP2();
    fn ADC1();
    fn LCD();
    fn SDIO();
    fn ETH();
    fn CAN0();
    fn CAN1();
    fn USB();
    fn RTC();
    fn WDOG1();
    fn LETIMER1();
    fn TRNG0();
    fn QSPI0();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 68] = [
    Vector { _handler: EMU },
    Vector { _handler: WDOG0 },
    Vector { _handler: LDMA },
    Vector {
        _handler: GPIO_EVEN,
    },
    Vector { _handler: SMU },
    Vector { _handler: TIMER0 },
    Vector {
        _handler: USART0_RX,
    },
    Vector {
        _handler: USART0_TX,
    },
    Vector { _handler: ACMP0 },
    Vector { _handler: ADC0 },
    Vector { _handler: IDAC0 },
    Vector { _handler: I2C0 },
    Vector { _handler: I2C1 },
    Vector { _handler: GPIO_ODD },
    Vector { _handler: TIMER1 },
    Vector { _handler: TIMER2 },
    Vector { _handler: TIMER3 },
    Vector {
        _handler: USART1_RX,
    },
    Vector {
        _handler: USART1_TX,
    },
    Vector {
        _handler: USART2_RX,
    },
    Vector {
        _handler: USART2_TX,
    },
    Vector { _handler: UART0_RX },
    Vector { _handler: UART0_TX },
    Vector { _handler: UART1_RX },
    Vector { _handler: UART1_TX },
    Vector { _handler: LEUART0 },
    Vector { _handler: LEUART1 },
    Vector { _handler: LETIMER0 },
    Vector { _handler: PCNT0 },
    Vector { _handler: PCNT1 },
    Vector { _handler: PCNT2 },
    Vector { _handler: RTCC },
    Vector { _handler: CMU },
    Vector { _handler: MSC },
    Vector { _handler: CRYPTO0 },
    Vector {
        _handler: CRYOTIMER,
    },
    Vector { _handler: FPUEH },
    Vector {
        _handler: USART3_RX,
    },
    Vector {
        _handler: USART3_TX,
    },
    Vector {
        _handler: USART4_RX,
    },
    Vector {
        _handler: USART4_TX,
    },
    Vector { _handler: WTIMER0 },
    Vector { _handler: WTIMER1 },
    Vector { _handler: WTIMER2 },
    Vector { _handler: WTIMER3 },
    Vector { _handler: I2C2 },
    Vector { _handler: VDAC0 },
    Vector { _handler: TIMER4 },
    Vector { _handler: TIMER5 },
    Vector { _handler: TIMER6 },
    Vector {
        _handler: USART5_RX,
    },
    Vector {
        _handler: USART5_TX,
    },
    Vector { _handler: CSEN },
    Vector { _handler: LESENSE },
    Vector { _handler: EBI },
    Vector { _handler: ACMP2 },
    Vector { _handler: ADC1 },
    Vector { _handler: LCD },
    Vector { _handler: SDIO },
    Vector { _handler: ETH },
    Vector { _handler: CAN0 },
    Vector { _handler: CAN1 },
    Vector { _handler: USB },
    Vector { _handler: RTC },
    Vector { _handler: WDOG1 },
    Vector { _handler: LETIMER1 },
    Vector { _handler: TRNG0 },
    Vector { _handler: QSPI0 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - EMU"]
    EMU = 0,
    #[doc = "1 - WDOG0"]
    WDOG0 = 1,
    #[doc = "2 - LDMA"]
    LDMA = 2,
    #[doc = "3 - GPIO_EVEN"]
    GPIO_EVEN = 3,
    #[doc = "4 - SMU"]
    SMU = 4,
    #[doc = "5 - TIMER0"]
    TIMER0 = 5,
    #[doc = "6 - USART0_RX"]
    USART0_RX = 6,
    #[doc = "7 - USART0_TX"]
    USART0_TX = 7,
    #[doc = "8 - ACMP0"]
    ACMP0 = 8,
    #[doc = "9 - ADC0"]
    ADC0 = 9,
    #[doc = "10 - IDAC0"]
    IDAC0 = 10,
    #[doc = "11 - I2C0"]
    I2C0 = 11,
    #[doc = "12 - I2C1"]
    I2C1 = 12,
    #[doc = "13 - GPIO_ODD"]
    GPIO_ODD = 13,
    #[doc = "14 - TIMER1"]
    TIMER1 = 14,
    #[doc = "15 - TIMER2"]
    TIMER2 = 15,
    #[doc = "16 - TIMER3"]
    TIMER3 = 16,
    #[doc = "17 - USART1_RX"]
    USART1_RX = 17,
    #[doc = "18 - USART1_TX"]
    USART1_TX = 18,
    #[doc = "19 - USART2_RX"]
    USART2_RX = 19,
    #[doc = "20 - USART2_TX"]
    USART2_TX = 20,
    #[doc = "21 - UART0_RX"]
    UART0_RX = 21,
    #[doc = "22 - UART0_TX"]
    UART0_TX = 22,
    #[doc = "23 - UART1_RX"]
    UART1_RX = 23,
    #[doc = "24 - UART1_TX"]
    UART1_TX = 24,
    #[doc = "25 - LEUART0"]
    LEUART0 = 25,
    #[doc = "26 - LEUART1"]
    LEUART1 = 26,
    #[doc = "27 - LETIMER0"]
    LETIMER0 = 27,
    #[doc = "28 - PCNT0"]
    PCNT0 = 28,
    #[doc = "29 - PCNT1"]
    PCNT1 = 29,
    #[doc = "30 - PCNT2"]
    PCNT2 = 30,
    #[doc = "31 - RTCC"]
    RTCC = 31,
    #[doc = "32 - CMU"]
    CMU = 32,
    #[doc = "33 - MSC"]
    MSC = 33,
    #[doc = "34 - CRYPTO0"]
    CRYPTO0 = 34,
    #[doc = "35 - CRYOTIMER"]
    CRYOTIMER = 35,
    #[doc = "36 - FPUEH"]
    FPUEH = 36,
    #[doc = "37 - USART3_RX"]
    USART3_RX = 37,
    #[doc = "38 - USART3_TX"]
    USART3_TX = 38,
    #[doc = "39 - USART4_RX"]
    USART4_RX = 39,
    #[doc = "40 - USART4_TX"]
    USART4_TX = 40,
    #[doc = "41 - WTIMER0"]
    WTIMER0 = 41,
    #[doc = "42 - WTIMER1"]
    WTIMER1 = 42,
    #[doc = "43 - WTIMER2"]
    WTIMER2 = 43,
    #[doc = "44 - WTIMER3"]
    WTIMER3 = 44,
    #[doc = "45 - I2C2"]
    I2C2 = 45,
    #[doc = "46 - VDAC0"]
    VDAC0 = 46,
    #[doc = "47 - TIMER4"]
    TIMER4 = 47,
    #[doc = "48 - TIMER5"]
    TIMER5 = 48,
    #[doc = "49 - TIMER6"]
    TIMER6 = 49,
    #[doc = "50 - USART5_RX"]
    USART5_RX = 50,
    #[doc = "51 - USART5_TX"]
    USART5_TX = 51,
    #[doc = "52 - CSEN"]
    CSEN = 52,
    #[doc = "53 - LESENSE"]
    LESENSE = 53,
    #[doc = "54 - EBI"]
    EBI = 54,
    #[doc = "55 - ACMP2"]
    ACMP2 = 55,
    #[doc = "56 - ADC1"]
    ADC1 = 56,
    #[doc = "57 - LCD"]
    LCD = 57,
    #[doc = "58 - SDIO"]
    SDIO = 58,
    #[doc = "59 - ETH"]
    ETH = 59,
    #[doc = "60 - CAN0"]
    CAN0 = 60,
    #[doc = "61 - CAN1"]
    CAN1 = 61,
    #[doc = "62 - USB"]
    USB = 62,
    #[doc = "63 - RTC"]
    RTC = 63,
    #[doc = "64 - WDOG1"]
    WDOG1 = 64,
    #[doc = "65 - LETIMER1"]
    LETIMER1 = 65,
    #[doc = "66 - TRNG0"]
    TRNG0 = 66,
    #[doc = "67 - QSPI0"]
    QSPI0 = 67,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "The DI page contains calibration values, a unique identification number and other useful data"]
pub type Devinfo = crate::Periph<devinfo::RegisterBlock, 0x0fe0_81b0>;
impl core::fmt::Debug for Devinfo {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Devinfo").finish()
    }
}
#[doc = "The DI page contains calibration values, a unique identification number and other useful data"]
pub mod devinfo;
#[doc = "MSC"]
pub type Msc = crate::Periph<msc::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Msc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Msc").finish()
    }
}
#[doc = "MSC"]
pub mod msc;
#[doc = "EMU"]
pub type Emu = crate::Periph<emu::RegisterBlock, 0x400e_3000>;
impl core::fmt::Debug for Emu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Emu").finish()
    }
}
#[doc = "EMU"]
pub mod emu;
#[doc = "RMU"]
pub type Rmu = crate::Periph<rmu::RegisterBlock, 0x400e_5000>;
impl core::fmt::Debug for Rmu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rmu").finish()
    }
}
#[doc = "RMU"]
pub mod rmu;
#[doc = "CMU"]
pub type Cmu = crate::Periph<cmu::RegisterBlock, 0x400e_4000>;
impl core::fmt::Debug for Cmu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmu").finish()
    }
}
#[doc = "CMU"]
pub mod cmu;
#[doc = "CRYPTO0"]
pub type Crypto0 = crate::Periph<crypto0::RegisterBlock, 0x400f_0000>;
impl core::fmt::Debug for Crypto0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crypto0").finish()
    }
}
#[doc = "CRYPTO0"]
pub mod crypto0;
#[doc = "LESENSE"]
pub type Lesense = crate::Periph<lesense::RegisterBlock, 0x4005_5000>;
impl core::fmt::Debug for Lesense {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lesense").finish()
    }
}
#[doc = "LESENSE"]
pub mod lesense;
#[doc = "EBI"]
pub type Ebi = crate::Periph<ebi::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Ebi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ebi").finish()
    }
}
#[doc = "EBI"]
pub mod ebi;
#[doc = "ETH"]
pub type Eth = crate::Periph<eth::RegisterBlock, 0x4002_4000>;
impl core::fmt::Debug for Eth {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Eth").finish()
    }
}
#[doc = "ETH"]
pub mod eth;
#[doc = "SDIO"]
pub type Sdio = crate::Periph<sdio::RegisterBlock, 0x400f_1000>;
impl core::fmt::Debug for Sdio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sdio").finish()
    }
}
#[doc = "SDIO"]
pub mod sdio;
#[doc = "GPIO"]
pub type Gpio = crate::Periph<gpio::RegisterBlock, 0x4008_8000>;
impl core::fmt::Debug for Gpio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio").finish()
    }
}
#[doc = "GPIO"]
pub mod gpio;
#[doc = "PRS"]
pub type Prs = crate::Periph<prs::RegisterBlock, 0x400e_6000>;
impl core::fmt::Debug for Prs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Prs").finish()
    }
}
#[doc = "PRS"]
pub mod prs;
#[doc = "LDMA"]
pub type Ldma = crate::Periph<ldma::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Ldma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ldma").finish()
    }
}
#[doc = "LDMA"]
pub mod ldma;
#[doc = "FPUEH"]
pub type Fpueh = crate::Periph<fpueh::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Fpueh {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Fpueh").finish()
    }
}
#[doc = "FPUEH"]
pub mod fpueh;
#[doc = "GPCRC"]
pub type Gpcrc = crate::Periph<gpcrc::RegisterBlock, 0x4001_c000>;
impl core::fmt::Debug for Gpcrc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpcrc").finish()
    }
}
#[doc = "GPCRC"]
pub mod gpcrc;
#[doc = "CAN0"]
pub type Can0 = crate::Periph<can0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Can0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Can0").finish()
    }
}
#[doc = "CAN0"]
pub mod can0;
#[doc = "CAN1"]
pub type Can1 = crate::Periph<can1::RegisterBlock, 0x4000_4400>;
impl core::fmt::Debug for Can1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Can1").finish()
    }
}
#[doc = "CAN1"]
pub mod can1;
#[doc = "TIMER0"]
pub type Timer0 = crate::Periph<timer0::RegisterBlock, 0x4001_8000>;
impl core::fmt::Debug for Timer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0").finish()
    }
}
#[doc = "TIMER0"]
pub mod timer0;
#[doc = "TIMER1"]
pub type Timer1 = crate::Periph<timer1::RegisterBlock, 0x4001_8400>;
impl core::fmt::Debug for Timer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1").finish()
    }
}
#[doc = "TIMER1"]
pub mod timer1;
#[doc = "TIMER2"]
pub type Timer2 = crate::Periph<timer2::RegisterBlock, 0x4001_8800>;
impl core::fmt::Debug for Timer2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2").finish()
    }
}
#[doc = "TIMER2"]
pub mod timer2;
#[doc = "TIMER3"]
pub type Timer3 = crate::Periph<timer3::RegisterBlock, 0x4001_8c00>;
impl core::fmt::Debug for Timer3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer3").finish()
    }
}
#[doc = "TIMER3"]
pub mod timer3;
#[doc = "TIMER4"]
pub type Timer4 = crate::Periph<timer4::RegisterBlock, 0x4001_9000>;
impl core::fmt::Debug for Timer4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer4").finish()
    }
}
#[doc = "TIMER4"]
pub mod timer4;
#[doc = "TIMER5"]
pub type Timer5 = crate::Periph<timer5::RegisterBlock, 0x4001_9400>;
impl core::fmt::Debug for Timer5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer5").finish()
    }
}
#[doc = "TIMER5"]
pub mod timer5;
#[doc = "TIMER6"]
pub type Timer6 = crate::Periph<timer6::RegisterBlock, 0x4001_9800>;
impl core::fmt::Debug for Timer6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer6").finish()
    }
}
#[doc = "TIMER6"]
pub mod timer6;
#[doc = "WTIMER0"]
pub type Wtimer0 = crate::Periph<wtimer0::RegisterBlock, 0x4001_a000>;
impl core::fmt::Debug for Wtimer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wtimer0").finish()
    }
}
#[doc = "WTIMER0"]
pub mod wtimer0;
#[doc = "WTIMER1"]
pub type Wtimer1 = crate::Periph<wtimer1::RegisterBlock, 0x4001_a400>;
impl core::fmt::Debug for Wtimer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wtimer1").finish()
    }
}
#[doc = "WTIMER1"]
pub mod wtimer1;
#[doc = "WTIMER2"]
pub type Wtimer2 = crate::Periph<wtimer2::RegisterBlock, 0x4001_a800>;
impl core::fmt::Debug for Wtimer2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wtimer2").finish()
    }
}
#[doc = "WTIMER2"]
pub mod wtimer2;
#[doc = "WTIMER3"]
pub type Wtimer3 = crate::Periph<wtimer3::RegisterBlock, 0x4001_ac00>;
impl core::fmt::Debug for Wtimer3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wtimer3").finish()
    }
}
#[doc = "WTIMER3"]
pub mod wtimer3;
#[doc = "USART0"]
pub type Usart0 = crate::Periph<usart0::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Usart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart0").finish()
    }
}
#[doc = "USART0"]
pub mod usart0;
#[doc = "USART1"]
pub type Usart1 = crate::Periph<usart1::RegisterBlock, 0x4001_0400>;
impl core::fmt::Debug for Usart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart1").finish()
    }
}
#[doc = "USART1"]
pub mod usart1;
#[doc = "USART2"]
pub type Usart2 = crate::Periph<usart2::RegisterBlock, 0x4001_0800>;
impl core::fmt::Debug for Usart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart2").finish()
    }
}
#[doc = "USART2"]
pub mod usart2;
#[doc = "USART3"]
pub type Usart3 = crate::Periph<usart3::RegisterBlock, 0x4001_0c00>;
impl core::fmt::Debug for Usart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart3").finish()
    }
}
#[doc = "USART3"]
pub mod usart3;
#[doc = "USART4"]
pub type Usart4 = crate::Periph<usart4::RegisterBlock, 0x4001_1000>;
impl core::fmt::Debug for Usart4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart4").finish()
    }
}
#[doc = "USART4"]
pub mod usart4;
#[doc = "USART5"]
pub type Usart5 = crate::Periph<usart5::RegisterBlock, 0x4001_1400>;
impl core::fmt::Debug for Usart5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart5").finish()
    }
}
#[doc = "USART5"]
pub mod usart5;
#[doc = "UART0"]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "UART0"]
pub mod uart0;
#[doc = "UART1"]
pub type Uart1 = crate::Periph<uart1::RegisterBlock, 0x4001_4400>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "UART1"]
pub mod uart1;
#[doc = "QSPI0"]
pub type Qspi0 = crate::Periph<qspi0::RegisterBlock, 0x4001_c400>;
impl core::fmt::Debug for Qspi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qspi0").finish()
    }
}
#[doc = "QSPI0"]
pub mod qspi0;
#[doc = "LEUART0"]
pub type Leuart0 = crate::Periph<leuart0::RegisterBlock, 0x4006_a000>;
impl core::fmt::Debug for Leuart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Leuart0").finish()
    }
}
#[doc = "LEUART0"]
pub mod leuart0;
#[doc = "LEUART1"]
pub type Leuart1 = crate::Periph<leuart1::RegisterBlock, 0x4006_a400>;
impl core::fmt::Debug for Leuart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Leuart1").finish()
    }
}
#[doc = "LEUART1"]
pub mod leuart1;
#[doc = "LETIMER0"]
pub type Letimer0 = crate::Periph<letimer0::RegisterBlock, 0x4006_6000>;
impl core::fmt::Debug for Letimer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Letimer0").finish()
    }
}
#[doc = "LETIMER0"]
pub mod letimer0;
#[doc = "LETIMER1"]
pub type Letimer1 = crate::Periph<letimer1::RegisterBlock, 0x4006_6400>;
impl core::fmt::Debug for Letimer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Letimer1").finish()
    }
}
#[doc = "LETIMER1"]
pub mod letimer1;
#[doc = "CRYOTIMER"]
pub type Cryotimer = crate::Periph<cryotimer::RegisterBlock, 0x4008_f000>;
impl core::fmt::Debug for Cryotimer {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cryotimer").finish()
    }
}
#[doc = "CRYOTIMER"]
pub mod cryotimer;
#[doc = "PCNT0"]
pub type Pcnt0 = crate::Periph<pcnt0::RegisterBlock, 0x4006_e000>;
impl core::fmt::Debug for Pcnt0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pcnt0").finish()
    }
}
#[doc = "PCNT0"]
pub mod pcnt0;
#[doc = "PCNT1"]
pub type Pcnt1 = crate::Periph<pcnt1::RegisterBlock, 0x4006_e400>;
impl core::fmt::Debug for Pcnt1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pcnt1").finish()
    }
}
#[doc = "PCNT1"]
pub mod pcnt1;
#[doc = "PCNT2"]
pub type Pcnt2 = crate::Periph<pcnt2::RegisterBlock, 0x4006_e800>;
impl core::fmt::Debug for Pcnt2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pcnt2").finish()
    }
}
#[doc = "PCNT2"]
pub mod pcnt2;
#[doc = "I2C0"]
pub type I2c0 = crate::Periph<i2c0::RegisterBlock, 0x4008_9000>;
impl core::fmt::Debug for I2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0").finish()
    }
}
#[doc = "I2C0"]
pub mod i2c0;
#[doc = "I2C1"]
pub type I2c1 = crate::Periph<i2c1::RegisterBlock, 0x4008_9400>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "I2C1"]
pub mod i2c1;
#[doc = "I2C2"]
pub type I2c2 = crate::Periph<i2c2::RegisterBlock, 0x4008_9800>;
impl core::fmt::Debug for I2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c2").finish()
    }
}
#[doc = "I2C2"]
pub mod i2c2;
#[doc = "ADC0"]
pub type Adc0 = crate::Periph<adc0::RegisterBlock, 0x4008_2000>;
impl core::fmt::Debug for Adc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc0").finish()
    }
}
#[doc = "ADC0"]
pub mod adc0;
#[doc = "ADC1"]
pub type Adc1 = crate::Periph<adc1::RegisterBlock, 0x4008_2400>;
impl core::fmt::Debug for Adc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc1").finish()
    }
}
#[doc = "ADC1"]
pub mod adc1;
#[doc = "ACMP0"]
pub type Acmp0 = crate::Periph<acmp0::RegisterBlock, 0x4008_0000>;
impl core::fmt::Debug for Acmp0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Acmp0").finish()
    }
}
#[doc = "ACMP0"]
pub mod acmp0;
#[doc = "ACMP1"]
pub type Acmp1 = crate::Periph<acmp1::RegisterBlock, 0x4008_0400>;
impl core::fmt::Debug for Acmp1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Acmp1").finish()
    }
}
#[doc = "ACMP1"]
pub mod acmp1;
#[doc = "ACMP2"]
pub type Acmp2 = crate::Periph<acmp2::RegisterBlock, 0x4008_0800>;
impl core::fmt::Debug for Acmp2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Acmp2").finish()
    }
}
#[doc = "ACMP2"]
pub mod acmp2;
#[doc = "ACMP3"]
pub type Acmp3 = crate::Periph<acmp3::RegisterBlock, 0x4008_0c00>;
impl core::fmt::Debug for Acmp3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Acmp3").finish()
    }
}
#[doc = "ACMP3"]
pub mod acmp3;
#[doc = "VDAC0"]
pub type Vdac0 = crate::Periph<vdac0::RegisterBlock, 0x4008_6000>;
impl core::fmt::Debug for Vdac0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vdac0").finish()
    }
}
#[doc = "VDAC0"]
pub mod vdac0;
#[doc = "USB"]
pub type Usb = crate::Periph<usb::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for Usb {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usb").finish()
    }
}
#[doc = "USB"]
pub mod usb;
#[doc = "IDAC0"]
pub type Idac0 = crate::Periph<idac0::RegisterBlock, 0x4008_4000>;
impl core::fmt::Debug for Idac0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Idac0").finish()
    }
}
#[doc = "IDAC0"]
pub mod idac0;
#[doc = "CSEN"]
pub type Csen = crate::Periph<csen::RegisterBlock, 0x4008_e000>;
impl core::fmt::Debug for Csen {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Csen").finish()
    }
}
#[doc = "CSEN"]
pub mod csen;
#[doc = "LCD"]
pub type Lcd = crate::Periph<lcd::RegisterBlock, 0x4005_4000>;
impl core::fmt::Debug for Lcd {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lcd").finish()
    }
}
#[doc = "LCD"]
pub mod lcd;
#[doc = "RTC"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4006_0000>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "RTC"]
pub mod rtc;
#[doc = "RTCC"]
pub type Rtcc = crate::Periph<rtcc::RegisterBlock, 0x4006_2000>;
impl core::fmt::Debug for Rtcc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtcc").finish()
    }
}
#[doc = "RTCC"]
pub mod rtcc;
#[doc = "WDOG0"]
pub type Wdog0 = crate::Periph<wdog0::RegisterBlock, 0x4005_2000>;
impl core::fmt::Debug for Wdog0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdog0").finish()
    }
}
#[doc = "WDOG0"]
pub mod wdog0;
#[doc = "WDOG1"]
pub type Wdog1 = crate::Periph<wdog1::RegisterBlock, 0x4005_2400>;
impl core::fmt::Debug for Wdog1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdog1").finish()
    }
}
#[doc = "WDOG1"]
pub mod wdog1;
#[doc = "ETM"]
pub type Etm = crate::Periph<etm::RegisterBlock, 0xe004_1000>;
impl core::fmt::Debug for Etm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Etm").finish()
    }
}
#[doc = "ETM"]
pub mod etm;
#[doc = "SMU"]
pub type Smu = crate::Periph<smu::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Smu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Smu").finish()
    }
}
#[doc = "SMU"]
pub mod smu;
#[doc = "TRNG0"]
pub type Trng0 = crate::Periph<trng0::RegisterBlock, 0x4001_d000>;
impl core::fmt::Debug for Trng0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Trng0").finish()
    }
}
#[doc = "TRNG0"]
pub mod trng0;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "DEVINFO"]
    pub devinfo: Devinfo,
    #[doc = "MSC"]
    pub msc: Msc,
    #[doc = "EMU"]
    pub emu: Emu,
    #[doc = "RMU"]
    pub rmu: Rmu,
    #[doc = "CMU"]
    pub cmu: Cmu,
    #[doc = "CRYPTO0"]
    pub crypto0: Crypto0,
    #[doc = "LESENSE"]
    pub lesense: Lesense,
    #[doc = "EBI"]
    pub ebi: Ebi,
    #[doc = "ETH"]
    pub eth: Eth,
    #[doc = "SDIO"]
    pub sdio: Sdio,
    #[doc = "GPIO"]
    pub gpio: Gpio,
    #[doc = "PRS"]
    pub prs: Prs,
    #[doc = "LDMA"]
    pub ldma: Ldma,
    #[doc = "FPUEH"]
    pub fpueh: Fpueh,
    #[doc = "GPCRC"]
    pub gpcrc: Gpcrc,
    #[doc = "CAN0"]
    pub can0: Can0,
    #[doc = "CAN1"]
    pub can1: Can1,
    #[doc = "TIMER0"]
    pub timer0: Timer0,
    #[doc = "TIMER1"]
    pub timer1: Timer1,
    #[doc = "TIMER2"]
    pub timer2: Timer2,
    #[doc = "TIMER3"]
    pub timer3: Timer3,
    #[doc = "TIMER4"]
    pub timer4: Timer4,
    #[doc = "TIMER5"]
    pub timer5: Timer5,
    #[doc = "TIMER6"]
    pub timer6: Timer6,
    #[doc = "WTIMER0"]
    pub wtimer0: Wtimer0,
    #[doc = "WTIMER1"]
    pub wtimer1: Wtimer1,
    #[doc = "WTIMER2"]
    pub wtimer2: Wtimer2,
    #[doc = "WTIMER3"]
    pub wtimer3: Wtimer3,
    #[doc = "USART0"]
    pub usart0: Usart0,
    #[doc = "USART1"]
    pub usart1: Usart1,
    #[doc = "USART2"]
    pub usart2: Usart2,
    #[doc = "USART3"]
    pub usart3: Usart3,
    #[doc = "USART4"]
    pub usart4: Usart4,
    #[doc = "USART5"]
    pub usart5: Usart5,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "QSPI0"]
    pub qspi0: Qspi0,
    #[doc = "LEUART0"]
    pub leuart0: Leuart0,
    #[doc = "LEUART1"]
    pub leuart1: Leuart1,
    #[doc = "LETIMER0"]
    pub letimer0: Letimer0,
    #[doc = "LETIMER1"]
    pub letimer1: Letimer1,
    #[doc = "CRYOTIMER"]
    pub cryotimer: Cryotimer,
    #[doc = "PCNT0"]
    pub pcnt0: Pcnt0,
    #[doc = "PCNT1"]
    pub pcnt1: Pcnt1,
    #[doc = "PCNT2"]
    pub pcnt2: Pcnt2,
    #[doc = "I2C0"]
    pub i2c0: I2c0,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "I2C2"]
    pub i2c2: I2c2,
    #[doc = "ADC0"]
    pub adc0: Adc0,
    #[doc = "ADC1"]
    pub adc1: Adc1,
    #[doc = "ACMP0"]
    pub acmp0: Acmp0,
    #[doc = "ACMP1"]
    pub acmp1: Acmp1,
    #[doc = "ACMP2"]
    pub acmp2: Acmp2,
    #[doc = "ACMP3"]
    pub acmp3: Acmp3,
    #[doc = "VDAC0"]
    pub vdac0: Vdac0,
    #[doc = "USB"]
    pub usb: Usb,
    #[doc = "IDAC0"]
    pub idac0: Idac0,
    #[doc = "CSEN"]
    pub csen: Csen,
    #[doc = "LCD"]
    pub lcd: Lcd,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "RTCC"]
    pub rtcc: Rtcc,
    #[doc = "WDOG0"]
    pub wdog0: Wdog0,
    #[doc = "WDOG1"]
    pub wdog1: Wdog1,
    #[doc = "ETM"]
    pub etm: Etm,
    #[doc = "SMU"]
    pub smu: Smu,
    #[doc = "TRNG0"]
    pub trng0: Trng0,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            devinfo: Devinfo::steal(),
            msc: Msc::steal(),
            emu: Emu::steal(),
            rmu: Rmu::steal(),
            cmu: Cmu::steal(),
            crypto0: Crypto0::steal(),
            lesense: Lesense::steal(),
            ebi: Ebi::steal(),
            eth: Eth::steal(),
            sdio: Sdio::steal(),
            gpio: Gpio::steal(),
            prs: Prs::steal(),
            ldma: Ldma::steal(),
            fpueh: Fpueh::steal(),
            gpcrc: Gpcrc::steal(),
            can0: Can0::steal(),
            can1: Can1::steal(),
            timer0: Timer0::steal(),
            timer1: Timer1::steal(),
            timer2: Timer2::steal(),
            timer3: Timer3::steal(),
            timer4: Timer4::steal(),
            timer5: Timer5::steal(),
            timer6: Timer6::steal(),
            wtimer0: Wtimer0::steal(),
            wtimer1: Wtimer1::steal(),
            wtimer2: Wtimer2::steal(),
            wtimer3: Wtimer3::steal(),
            usart0: Usart0::steal(),
            usart1: Usart1::steal(),
            usart2: Usart2::steal(),
            usart3: Usart3::steal(),
            usart4: Usart4::steal(),
            usart5: Usart5::steal(),
            uart0: Uart0::steal(),
            uart1: Uart1::steal(),
            qspi0: Qspi0::steal(),
            leuart0: Leuart0::steal(),
            leuart1: Leuart1::steal(),
            letimer0: Letimer0::steal(),
            letimer1: Letimer1::steal(),
            cryotimer: Cryotimer::steal(),
            pcnt0: Pcnt0::steal(),
            pcnt1: Pcnt1::steal(),
            pcnt2: Pcnt2::steal(),
            i2c0: I2c0::steal(),
            i2c1: I2c1::steal(),
            i2c2: I2c2::steal(),
            adc0: Adc0::steal(),
            adc1: Adc1::steal(),
            acmp0: Acmp0::steal(),
            acmp1: Acmp1::steal(),
            acmp2: Acmp2::steal(),
            acmp3: Acmp3::steal(),
            vdac0: Vdac0::steal(),
            usb: Usb::steal(),
            idac0: Idac0::steal(),
            csen: Csen::steal(),
            lcd: Lcd::steal(),
            rtc: Rtc::steal(),
            rtcc: Rtcc::steal(),
            wdog0: Wdog0::steal(),
            wdog1: Wdog1::steal(),
            etm: Etm::steal(),
            smu: Smu::steal(),
            trng0: Trng0::steal(),
        }
    }
}
